/**:
  ros__parameters:
    # erpm (electrical rpm) = speed_to_erpm_gain * speed (meters / second) + speed_to_erpm_offset
    speed_to_erpm_gain: 4300.0  #4614.0
    speed_to_erpm_offset: 0.0

    # servo value (0 to 1) =  steering_angle_to_servo_gain * steering angle (radians) + steering_angle_to_servo_offset
    steering_angle_to_servo_gain: -0.87  #-1.2135
    steering_angle_to_servo_offset: 0.500 # 0.505 # 0.5304

    port: /dev/sensors/vesc
    duty_cycle_min: 0.0
    duty_cycle_max: 0.0
    current_min: 0.0
    current_max: 100.0
    brake_min: -20000.0
    brake_max: +200000.0
    speed_min: -69000.0 # [ERPM]
    speed_max: +45000.0 # [ERPM]
    position_min: 0.0
    position_max: 0.0
    servo_min: 0.10 # servo position for maximum left steering
    servo_max: 0.90 # servo position for maximum right steering

vesc_to_odom_node:
  ros__parameters:
    odom_frame: odom
    base_frame: base_link
    # publish tf between odom and base_link
    publish_tf: false # set to false because EKF publishes tf
    use_servo_cmd_to_calc_angular_velocity: true
    wheelbase: 0.33 # [m]

throttle_interpolator:
  ros__parameters:
    rpm_input_topic: commands/motor/unsmoothed_speed
    rpm_output_topic: commands/motor/speed
    servo_input_topic: commands/servo/unsmoothed_position
    servo_output_topic: commands/servo/position

    # servo smoother - limits acceleration and smooths anything above limit
    max_acceleration: 2.5 # [m/s^2]
    throttle_smoother_rate: 75.0 # [Hz]
    # servo smoother - limits rotation speed and smooths anything above limit
    max_servo_speed: 3.2 # [rad/s]
    servo_smoother_rate: 75.0 # [Hz]
